[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf

monitor_speed = 115200

test_framework = unity
test_ignore = test_desktop
test_build_src = yes

test_filter = *
build_src_filter = +<*> -<main.cpp>

build_flags =
    -Wno-error

build_unflags =
    -fuse-cxa-atexit

check_tool = cppcheck
check_skip_packages = yes

check_src_filters =
    +<src/>

check_flags =
    cppcheck: --inline-suppr --suppress=missingIncludeSystem --suppress=missingInclude --enable=warning,portability