[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
test_ignore = test_desktop
build_flags = 
    -Wno-error

check_tool = cppcheck
check_skip_packages = yes
check_src_filters = 
    +<src/>
check_flags =
    cppcheck: --inline-suppr --suppress=missingIncludeSystem --suppress=missingInclude